# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
    branches:
        develop:
            - step:
                name: Build and Deploy to GiantTiger-QA
                deployment: test
                script:
                  - node --version
                  - npm --version
                  - npm install -g npm 
                  - npm install
                  - npm install -g grunt-cli
                  - npm install grunt --save-dev
                  - cp mozu.config.json.gt-qa mozu.config.json
                  - grunt
                  - grunt newer-clean